# Generated by Django 5.2.1 on 2025-06-05 16:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "book_id",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                ("isbn", models.CharField(max_length=13, unique=True)),
                ("authors", models.CharField(max_length=255)),
                (
                    "publication_year",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(-1000),
                            django.core.validators.MaxValueValidator(2026),
                        ]
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("language", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "book",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="availability",
                        serialize=False,
                        to="catalog.book",
                    ),
                ),
                ("total_copies", models.IntegerField(default=0)),
                ("available_copies", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Book Availability",
                "verbose_name_plural": "Book Availabilities",
            },
        ),
        migrations.CreateModel(
            name="AmazonLink",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "book_id",
                        "url",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.URLField()),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amazon_links",
                        to="catalog.book",
                    ),
                ),
            ],
            options={
                "verbose_name": "Book link On Amazon",
                "verbose_name_plural": "Book Links on Amazon",
            },
        ),
        migrations.CreateModel(
            name="Borrows",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "user_id",
                        "book_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("returned", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="borrowed_by",
                        to="catalog.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="borrowed_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "user_id",
                        "book_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlisted_by",
                        to="catalog.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Wishlist Item",
                "verbose_name_plural": "Wishlist Items",
            },
        ),
    ]
